---
title: "Exploratory"
date: "12/4/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Data manipulation


```{r, message = FALSE}
cancer_df <-
  read_csv("Cancer_Registry.csv") %>% 
  janitor::clean_names() %>%
  separate(geography, into = c("county", "state"), sep = ",") %>%
  select(-pct_no_hs18_24, -pct_some_col18_24, -binned_inc) %>%     # lots of same county names, so I did not remove state column #
  arrange(county)
  
colSums(is.na(cancer_df))                             # check number of missing values #
cancer_df = 
  cancer_df %>%
  select(-pct_employed16_over, -pct_private_coverage_alone) %>%
  mutate(pct_white = ifelse(pct_white > 75, 1, 0)) %>% # 1 represents high percentage of white #
  select(target_death_rate, everything()) %>% 
  mutate(state = fct_reorder(state, target_death_rate))
str(cancer_df)
cancer_df %>% 
  lm(target_death_rate ~ state, data = .) %>% summary()

cancer_df=
  cancer_df %>%
  select(-state, -county)


mult.fit <- lm(target_death_rate ~ ., data=cancer_df)     # stepwise regression, and get 17 variables left#
step(mult.fit, direction='both')

seventeen_variable = cancer_df %>%
  select(target_death_rate, avg_ann_count , avg_deaths_per_year , 
     incidence_rate , pop_est2015 , poverty_percent ,median_age_male , 
     percent_married , pct_hs18_24 , pct_hs25_over , pct_bach_deg25_over , 
     pct_unemployed16_over , pct_private_coverage , pct_emp_priv_coverage , 
    pct_white , pct_other_race , pct_married_households , birth_rate)
round(cor(seventeen_variable),3)                    # correlation matrix #
step1=lm(target_death_rate ~ avg_ann_count  + 
     incidence_rate + pop_est2015 + poverty_percent + median_age_male + 
     percent_married + pct_hs18_24 + pct_hs25_over + pct_bach_deg25_over + 
     pct_unemployed16_over + pct_private_coverage + pct_emp_priv_coverage + 
     pct_white + pct_other_race + pct_married_households + birth_rate, 
     data = seventeen_variable)
summary(step1)
step2= lm(target_death_rate ~ avg_deaths_per_year  + 
     incidence_rate + pop_est2015 + poverty_percent + median_age_male + 
     percent_married + pct_hs18_24 + pct_hs25_over + pct_bach_deg25_over + 
     pct_unemployed16_over + pct_private_coverage + pct_emp_priv_coverage + 
     pct_white + pct_other_race + pct_married_households + birth_rate, 
     data = seventeen_variable)
summary(step2)
```
* "avg_deaths_per_year" and "not avg_ann_count" are highly correlated. The last two steps show that we should choose avg_deaths_per_year, not avg_ann_count. 
